stages:
  - build
  - test
  - static_analysis
  - sbom_scan
  - deploy

static_analysis:
  image: node:18-bullseye
  stage: static_analysis
  variables:
    DD_SITE: "datadoghq.com"
  before_script:
    - apt-get update && apt-get install -y unzip curl
    - npm install -g @datadog/datadog-ci
    - export DATADOG_STATIC_ANALYZER_URL=https://github.com/DataDog/datadog-static-analyzer/releases/latest/download/datadog-static-analyzer-x86_64-unknown-linux-gnu.zip
    - curl -L $DATADOG_STATIC_ANALYZER_URL > /tmp/ddog-static-analyzer.zip
    - unzip /tmp/ddog-static-analyzer.zip -d /tmp
    - mv /tmp/datadog-static-analyzer /usr/local/datadog-static-analyzer
    - chmod +x /usr/local/datadog-static-analyzer
  script:
    - /usr/local/datadog-static-analyzer -i . -o /tmp/report.sarif -f sarif
    - datadog-ci sarif upload /tmp/report.sarif

sbom_scan:
  image: node:18-bullseye
  stage: sbom_scan
  variables:
    DD_SITE: "datadoghq.com"
  before_script:
    - apt-get update && apt-get install -y unzip curl
    - npm install -g @datadog/datadog-ci
    - mkdir /osv-scanner
    - export DATADOG_OSV_SCANNER_URL=https://github.com/DataDog/osv-scanner/releases/latest/download/osv-scanner_linux_amd64.zip
    - curl -L -o /osv-scanner/osv-scanner.zip $DATADOG_OSV_SCANNER_URL
    - unzip /osv-scanner/osv-scanner.zip -d /osv-scanner
    - chmod 755 /osv-scanner/osv-scanner
  script:
    - /osv-scanner/osv-scanner --skip-git -r --experimental-only-packages --format=cyclonedx-1-5 --paths-relative-to-scan-dir --output=/tmp/sbom.json .
    - datadog-ci sbom upload /tmp/sbom.json
